[package]
name = "paperui-theme-eink"
version = "0.1.0"
edition = "2021"

[dependencies]
paperui-core = { path = "../paperui-core" }
paperui-widgets = { path = "../paperui-widgets" }

[dev-dependencies]
paperui-core = { path = "../paperui-core", features = ["mock"] }

[features]
mock = ["paperui-core/mock"]
